ensemble:
  name: null
feature:
- name: NormalizeFeatures
hpo:
  max_evals: 10
  name: random
models:
- hp_space:
  - feasiblePoints: 2,3
    parameterName: num_layers
    type: DISCRETE
  - cutFunc: lambda x:x[0] - 1
    cutPara:
    - num_layers
    length: 2
    maxValue:
    - 256
    - 256
    minValue:
    - 64
    - 64
    numericalType: INTEGER
    parameterName: hidden
    scalingType: LOG
    type: NUMERICAL_LIST
  - maxValue: 0.2
    minValue: 0.0
    parameterName: dropout
    scalingType: LINEAR
    type: DOUBLE
  - feasiblePoints:
    - leaky_relu
    - relu
    - elu
    - tanh
    parameterName: act
    type: CATEGORICAL
  name: gcn-model
trainer:
  hp_space:
  - maxValue: 150
    minValue: 50
    parameterName: max_epoch
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 40
    minValue: 25
    parameterName: early_stopping_round
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 0.05
    minValue: 0.005
    parameterName: lr
    scalingType: LOG
    type: DOUBLE
  - maxValue: 1.0E-7
    minValue: 1.0E-10
    parameterName: weight_decay
    scalingType: LOG
    type: DOUBLE
