ensemble:
  name: null
feature:
- name: PYGNormalizeFeatures
hpo:
  max_evals: 10
  name: random
nas:
  space:
    name: graphnas
    hidden_dim: 64
    layer_number: 2
  algorithm:
    name: rl
    num_epochs: 200
  estimator:
    name: scratch_hardware
models: []
trainer:
  hp_space:
  - maxValue: 300
    minValue: 100
    parameterName: max_epoch
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 30
    minValue: 10
    parameterName: early_stopping_round
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 0.05
    minValue: 0.01
    parameterName: lr
    scalingType: LOG
    type: DOUBLE
  - maxValue: 0.0005
    minValue: 5.0e-05
    parameterName: weight_decay
    scalingType: LOG
    type: DOUBLE
