ensemble:
  name: null
feature:
- name: NormalizeFeatures
hpo:
  max_evals: 10
  name: random
nas:
  space:
    name: autoattend
    hidden_dim: 64
    layer_number: 2
    dropout: 0.7
  algorithm:
    name: spos
    n_warmup: 2000  #2000
    population_size: 500
    cycles: 50 #　5
    sample_size : 100
  estimator:
    name: oneshot
models: []
trainer:
  hp_space:
  - maxValue: 300
    minValue: 100
    parameterName: max_epoch
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 30
    minValue: 10
    parameterName: early_stopping_round
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 0.05
    minValue: 0.01
    parameterName: lr
    scalingType: LOG
    type: DOUBLE
  - maxValue: 0.0005
    minValue: 5.0e-05
    parameterName: weight_decay
    scalingType: LOG
    type: DOUBLE
