ensemble:
  name: null
feature:
- name: PYGNormalizeFeatures
hpo:
  max_evals: 10
  name: random
models:
- hp_space:
  - feasiblePoints: 2,3
    parameterName: num_layers
    type: DISCRETE
  - cutFunc: lambda x:x[0] - 1
    cutPara:
    - num_layers
    length: 2
    maxValue:
    - 32
    - 32
    minValue:
    - 8
    - 8
    numericalType: INTEGER
    parameterName: hidden
    scalingType: LOG
    type: NUMERICAL_LIST
  - maxValue: 0.5
    minValue: 0.2
    parameterName: dropout
    scalingType: LINEAR
    type: DOUBLE
  - feasiblePoints: 8,10,12
    parameterName: heads
    type: DISCRETE
  - feasiblePoints:
    - leaky_relu
    - relu
    - elu
    - tanh
    parameterName: act
    type: CATEGORICAL
  name: gat
trainer:
  hp_space:
  - maxValue: 400
    minValue: 250
    parameterName: max_epoch
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 40
    minValue: 25
    parameterName: early_stopping_round
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 0.05
    minValue: 0.01
    parameterName: lr
    scalingType: LOG
    type: DOUBLE
  - maxValue: 0.0005
    minValue: 0.0001
    parameterName: weight_decay
    scalingType: LOG
    type: DOUBLE
