ensemble:
  name: voting
  size: 2
feature:
- name: PYGNormalizeFeatures
hpo:
  max_evals: 50
  name: tpe
models:
- hp_space:
  - feasiblePoints: '2'
    parameterName: num_layers
    type: DISCRETE
  - feasiblePoints: 6,8,10,12
    parameterName: heads
    type: DISCRETE
  - cutFunc: lambda x:x[0] - 1
    cutPara:
    - num_layers
    length: 1
    maxValue:
    - 16
    minValue:
    - 4
    numericalType: INTEGER
    parameterName: hidden
    scalingType: LOG
    type: NUMERICAL_LIST
  - maxValue: 0.8
    minValue: 0.2
    parameterName: dropout
    scalingType: LINEAR
    type: DOUBLE
  - feasiblePoints:
    - leaky_relu
    - relu
    - elu
    - tanh
    parameterName: act
    type: CATEGORICAL
  name: gat
- hp_space:
  - feasiblePoints: '2'
    parameterName: num_layers
    type: DISCRETE
  - cutFunc: lambda x:x[0] - 1
    cutPara:
    - num_layers
    length: 1
    maxValue:
    - 64
    minValue:
    - 16
    numericalType: INTEGER
    parameterName: hidden
    scalingType: LOG
    type: NUMERICAL_LIST
  - maxValue: 0.8
    minValue: 0.2
    parameterName: dropout
    scalingType: LINEAR
    type: DOUBLE
  - feasiblePoints:
    - leaky_relu
    - relu
    - elu
    - tanh
    parameterName: act
    type: CATEGORICAL
  name: gcn
trainer:
  hp_space:
  - maxValue: 300
    minValue: 100
    parameterName: max_epoch
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 30
    minValue: 10
    parameterName: early_stopping_round
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 0.05
    minValue: 0.01
    parameterName: lr
    scalingType: LOG
    type: DOUBLE
  - maxValue: 0.001
    minValue: 0.0001
    parameterName: weight_decay
    scalingType: LOG
    type: DOUBLE

